- name: play level variables example
  hosts: local
  connection: local
  vars:
    course: Devops
    Duration: 10 hr
    Trainer: sivakumar
  tasks:
    - name: print course Information
      ansible.builtin.debug:
        msg: "Hello {{ course }} , has {{ Duration }} Duration from Trainer {{ Trainer }}"

    - name: print course Information again
      ansible.builtin.debug:
        msg: "Hello {{ course }}, has {{ Duration }} from Trainer {{ Trainer }}"
