- name: variables in file
  hosts: local
  connection: local
  vars_files:
    - vars_files.yaml
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Im learning {{ course }} with duration {{ duration }} from {{ Trainer }}"
