- name: variables from inventory
  hosts: frontend
  tasks:
    - name: vars inventory
      ansible.builtin.debug:
        msg: "Im learning course {{ COURSE }} in {{ DURATION }} from {{ TRAINER }}"
