- name: understand vars preference
  hosts: local
  connection: local
  # vars: #Global vars
  #   GREETING: "Hello from Play"
  # vars_files: #files
  #   - vars-files.yaml
  # vars_prompt: # Prompt
  #   - name: GREETING
  #     prompt: Please enter the greeting
  #     private: false
  tasks:
    - name: print the greeting
      #     vars: # task vars
      #       GREETING: "Hello from TASK"
      ansible.builtin.debug:
        msg: "{{ GREETING }}"
#1. arguments
#2. local Task
#3. file
#4. prompt
#5. play
