- name: playbook control
  hosts: frontend
  become: yes
  tasks:
    - name: #Check for OS Redhat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: #check for OS Debian
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
