- name: #install packages
  hosts: frontend
  connection: frontend
  become: yes
  tasks:
    - name: #install different packages
      ansible.builtin.package:
        name: { { item } }
        state: present
      loop:
        - mysql
        - zip
        - nodejs
