- name: install different packages
  hosts: frontend
  become: yes
  tasks:
    - name: Install package
      ansible.builtin.package:
        name: "{{ item }}"
        state: installed
      loop:
        - mysql
        - zip
        - nodejs
