#Install only required packages from list
- name: Install required packages
  hosts: frontend
  become: yes
  tasks:
    - name: only install
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "nodejs", state: "present" }
        - { name: "nginx", state: "absent" }
        - { name: "mysql", state: "present" }
        - { name: "zip", state: "present" }
