- name: functions basics
  hosts: local
  connection: local
  vars:
    Persons: "Amar,Akbar,Antony,Prasad"
  tasks:
    - name: print undefined name
      ansible.builtin.debug:
        msg: "Hello, {{ person | default('Mohan') }}"

    - name: print from the list
      ansible.builtin.debug:
        msg: "Hello, {{ Persons | split(',') }}"
