[frontend]
172.31.45.179 COURSE=Devops DURATION=10hr TRAINER=sivakumar ansible_user=ec2-user ansible_password=DevOps321
172.31.45.179 COURSE=Ansible DURATION=2hr TRAINER=Phaninder ansible_user=ec2-user ansible_password=DevOps321

[backend]
172.31.45.179

[database]
172.31.45.179

[local]
localhost

[local:vars]
COURSE=AWSCloud
DURATION=3 hr
TRAINER=SIVA
GREETING=Inventory