[frontend]
172.31.43.228 COURSE=Devops DURATION=10hr TRAINER=sivakumar ansible_user=ec2-user ansible_password=DevOps321
172.31.47.224 COURSE=Ansible DURATION=2hr TRAINER=Phaninder ansible_user=ec2-user ansible_password=DevOps321

[backend]
172.31.43.228
172.31.46.14

[database]
172.31.47.224

[local]
localhost

[local:vars]
COURSE=AWSCloud
DURATION=3 hr
TRAINER=SIVA
GREETING=Inventory